#!/usr/bin/env python3
"""
Google Sheet Dashboard Builder — Mogi Automation OS
Generates a Google Apps Script that builds an auto-updating dashboard from raw data.

Usage:
    python dashboard_generator.py --input data.csv --title "Sales Dashboard" --output Code.gs
    python dashboard_generator.py --input data.csv --title "KPI Tracker" --output Code.gs --metrics revenue,users,conversion

Output: Google Apps Script .gs file + instructions for importing into Google Sheets.
"""

import argparse
import csv
import os
import sys
from collections import Counter


def generate_dashboard_script(data_path, title, metrics=None):
    """Generate a complete Google Apps Script for a dashboard sheet."""
    # Read sample data to understand structure
    with open(data_path, "r", encoding="utf-8", errors="replace") as f:
        reader = csv.DictReader(f)
        headers = reader.fieldnames or []
        rows = list(reader)

    sample_size = min(10, len(rows))
    sample_data = rows[:sample_size]

    numeric_cols = []
    date_cols = []
    text_cols = []

    for col in headers:
        vals = [r.get(col, "").strip() for r in sample_data if r.get(col, "").strip()]
        if not vals:
            text_cols.append(col)
            continue
        try:
            float(vals[0].replace("$", "").replace(",", ""))
            numeric_cols.append(col)
        except ValueError:
            if any(c in col.lower() for c in ["date", "time", "created", "updated", "day", "month", "year"]):
                date_cols.append(col)
            else:
                text_cols.append(col)

    if metrics:
        metric_list = [m.strip() for m in metrics.split(",")]
    else:
        metric_list = numeric_cols[:3] if numeric_cols else [headers[0]]

    metric_refs = "\n".join(
        f"  const metric{i} = getMetricSummary(data, '{m}');"
        for i, m in enumerate(metric_list)
    )

    metric_writes = "\n".join(
        f'    sheet.getRange("B" + (4 + {i})).setValue(metric{i}.avg !== null ? metric{i}.avg : "N/A");'
        for i in range(len(metric_list))
    )

    metric_labels = "\n".join(
        f'    sheet.getRange("A" + (4 + {i})).setValue("{m}");'
        for i, m in enumerate(metric_list)
    )

    column_list = json.dumps(headers)

    script = f'''/**
 * {title} — Auto-Generated Dashboard
 * Generated by Mogi Automation OS
 * 
 * Instructions:
 * 1. Open your Google Sheet
 * 2. Extensions → Apps Script
 * 3. Paste this code
 * 4. Save and run "buildDashboard"
 * 5. To auto-refresh: set a trigger (clock icon) → onEdit or time-driven
 */

/**
 * Main function: builds the dashboard from raw data sheet.
 * Assumes raw data is in a sheet named "Data" starting at A1.
 */
function buildDashboard() {{
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  
  // Get or create dashboard sheet
  let sheet = ss.getSheetByName("Dashboard");
  if (!sheet) {{
    sheet = ss.insertSheet("Dashboard");
  }}
  sheet.clear();
  
  // Get data
  const dataSheet = ss.getSheetByName("Data");
  if (!dataSheet) {{
    sheet.getRange("A1").setValue("❌ No sheet named 'Data' found.");
    sheet.getRange("A2").setValue("Rename your data sheet to 'Data' or move it to the first position.");
    return;
  }}
  
  const dataRange = dataSheet.getDataRange();
  const values = dataRange.getValues();
  const headers = values[0];
  const rows = values.slice(1);
  
  if (rows.length === 0) {{
    sheet.getRange("A1").setValue("No data found.");
    return;
  }}
  
  // ── Build Dashboard ──
  
  // Title
  sheet.getRange("A1").setValue("{title}");
  sheet.getRange("A1").setFontSize(18).setFontWeight("bold");
  
  // Metadata
  sheet.getRange("A2").setValue("Last updated: " + new Date().toLocaleString());
  sheet.getRange("A2").setFontStyle("italic");
  
  // ── Summary Metrics ──
  sheet.getRange("A4").setValue("Metric").setFontWeight("bold");
  sheet.getRange("B4").setValue("Value").setFontWeight("bold");
  
{metric_labels}
{metric_writes}
  
  // ── Column Summary ──
  const summaryStart = 4 + {len(metric_list)} + 2;
  sheet.getRange("A" + summaryStart).setValue("Column Overview").setFontWeight("bold").setFontSize(14);
  sheet.getRange("A" + (summaryStart + 1)).setValue("Column").setFontWeight("bold");
  sheet.getRange("B" + (summaryStart + 1)).setValue("Type").setFontWeight("bold");
  sheet.getRange("C" + (summaryStart + 1)).setValue("Non-Empty").setFontWeight("bold");
  
  const columnTypes = {column_list};
  for (let i = 0; i < columnTypes.length; i++) {{
    const col = columnTypes[i];
    const colIndex = headers.indexOf(col);
    if (colIndex === -1) continue;
    const nonEmpty = rows.filter(r => r[colIndex] !== "").length;
    const colType = typeof rows[0][colIndex];
    sheet.getRange("A" + (summaryStart + 2 + i)).setValue(col);
    sheet.getRange("B" + (summaryStart + 2 + i)).setValue(colType);
    sheet.getRange("C" + (summaryStart + 2 + i)).setValue(nonEmpty + " / " + rows.length);
  }}
  
  // ── Formatting ──
  sheet.setColumnWidth(1, 250);
  sheet.setColumnWidth(2, 200);
  sheet.getRange("A4:B" + (4 + {len(metric_list)} - 1)).setBorder(true, true, true, true, true, true);
  
  SpreadsheetApp.flush();
}}

/**
 * Helper: calculate summary stats for a numeric column.
 */
function getMetricSummary(data, columnName) {{
  const headers = data[0];
  const rows = data.slice(1);
  const colIndex = headers.indexOf(columnName);
  
  if (colIndex === -1) return {{ min: null, max: null, avg: null, sum: null }};
  
  const nums = rows
    .map(r => parseFloat(String(r[colIndex]).replace(/[$€£,]/g, "")))
    .filter(n => !isNaN(n));
  
  if (nums.length === 0) return {{ min: null, max: null, avg: null, sum: null }};
  
  const sum = nums.reduce((a, b) => a + b, 0);
  return {{
    min: Math.min(...nums),
    max: Math.max(...nums),
    avg: Math.round((sum / nums.length) * 100) / 100,
    sum: Math.round(sum * 100) / 100
  }};
}}

/**
 * Helper: add a chart to the dashboard.
 */
function addChart(sheet, dataRange, chartTitle, xCol, yCol) {{
  const chart = sheet.newChart()
    .setChartType(Charts.ChartType.COLUMN)
    .addRange(dataRange)
    .setPosition(5, 5, 0, 0)
    .setOption("title", chartTitle)
    .setOption("width", 500)
    .setOption("height", 300)
    .build();
  sheet.insertChart(chart);
}}
'''

    return script


def main():
    parser = argparse.ArgumentParser(description="Generate Google Apps Script dashboard from CSV data.")
    parser.add_argument("--input", "-i", required=True, help="Sample CSV data file")
    parser.add_argument("--title", "-t", default="Dashboard", help="Dashboard title")
    parser.add_argument("--output", "-o", default="Code.gs", help="Output Apps Script file")
    parser.add_argument("--metrics", "-m", help="Comma-separated metric columns to highlight")
    args = parser.parse_args()

    if not os.path.exists(args.input):
        print(f"❌ File not found: {args.input}")
        sys.exit(1)

    script = generate_dashboard_script(args.input, args.title, args.metrics)

    with open(args.output, "w") as f:
        f.write(script)

    print(f"✅ Google Apps Script generated: {args.output}")
    print(f"\nTo use:")
    print(f"  1. Open your Google Sheet")
    print(f"  2. Rename your data sheet to 'Data'")
    print(f"  3. Extensions → Apps Script → paste {args.output}")
    print(f"  4. Save → Run 'buildDashboard'")


if __name__ == "__main__":
    main()
